name: pasal
description: "Nepali e-commerce platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1

  # State Management
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1

  # UI & Utilities
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  uuid: ^4.4.0
  palette_generator: ^0.3.3+2


  # New packages for local image selection
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/data.json
