name: pasal
description: "Nepali e-commerce platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1

  # State Management
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1

  # UI & Utilities
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
